[
  {
    "old_string": "\t\tadd_filter( 'product_type_selector', array( $this, 'add_product_type' ) );\n\t\tadd_filter( 'woocommerce_product_class', array( $this, 'product_class' ), 10, 2 );\n\t\tadd_action( 'init', array( $this, 'register_product_class' ), 5 );",
    "new_string": "\t\tadd_filter( 'product_type_selector', array( $this, 'add_product_type' ) );\n\t\tadd_filter( 'woocommerce_product_class', array( $this, 'product_class' ), 10, 2 );\n\t\t// Product class file loads on woocommerce_loaded so WC_Product_Simple exists.\n\t\tadd_action( 'woocommerce_loaded', array( $this, 'load_product_class' ), 5 );"
  },
  {
    "old_string": "\t/**\n\t * Register the product class if WC_Product_Simple is loaded.\n\t *\n\t * @return void\n\t */\n\tpublic function register_product_class() {\n\t\tif ( ! class_exists( 'WC_Product_Simple' ) || class_exists( 'WC_Product_Bookable_Tour' ) ) {\n\t\t\treturn;\n\t\t}\n\n\t\t/**\n\t\t * Bookable tour product class.\n\t\t */\n\t\tclass WC_Product_Bookable_Tour extends WC_Product_Simple {\n\n\t\t\t/**\n\t\t\t * Get internal type.\n\t\t\t *\n\t\t\t * @return string\n\t\t\t */\n\t\t\tpublic function get_type() {\n\t\t\t\treturn WC_Booking_Calendar_Product::PRODUCT_TYPE;\n\t\t\t}\n\n\t\t\t/**\n\t\t\t * No \"purchasable\" check fails — always purchasable.\n\t\t\t *\n\t\t\t * @return bool\n\t\t\t */\n\t\t\tpublic function is_purchasable() {\n\t\t\t\treturn true;\n\t\t\t}\n\n\t\t\t/**\n\t\t\t * Always virtual (no shipping).\n\t\t\t *\n\t\t\t * @return bool\n\t\t\t */\n\t\t\tpublic function is_virtual() {\n\t\t\t\treturn true;\n\t\t\t}\n\n\t\t\t/**\n\t\t\t * No stock management for bookings.\n\t\t\t *\n\t\t\t * @return bool\n\t\t\t */\n\t\t\tpublic function managing_stock() {\n\t\t\t\treturn false;\n\t\t\t}\n\t\t}\n\t}",
    "new_string": "\t/**\n\t * Load the product class (a separate file so we don't nest class decls).\n\t *\n\t * @return void\n\t */\n\tpublic function load_product_class() {\n\t\tif ( class_exists( 'WC_Product_Bookable_Tour' ) ) {\n\t\t\treturn;\n\t\t}\n\t\t$path = WC_BOOKING_CALENDAR_PLUGIN_DIR . 'includes/class-wc-product-bookable-tour.php';\n\t\tif ( file_exists( $path ) ) {\n\t\t\trequire_once $path;\n\t\t}\n\t}"
  }
]